--- 
pid: tmp/pids/thin.pid
adapter: rails
log: log/thin.log
timeout: 30
max_conns: 1024
port: 3000
chdir: /Users/scashin133/rails/personal/disneyland_helper
environment: development
max_persistent_conns: 512
servers: 1
daemonize: true
require: []

address: 0.0.0.0
